# This is a mapping configuration for value based data-reshape.

# Value based reshapings are heavily reliant on the
# assumtion that each group of related data-points
# can be reasonably identified as unique by a
# combination of their `node`, `sensor`, and `unit`
# values.  Ex: all data-points with `node=apples`,
# `sensor=oranges`, and `unit=carrots` can be
# acted upon as a singular group.

[settings]
is-active = false
uid-key = ["node","name","unit"] # defaults to ["node","name","unit"]
on-replace = "discard" # defaults to "discard"
on-filter = "discard" # possibilities: discard, archive
in-order = ["filter","replace","generate"]

[replace]
node1-sensor1-someunit = { name = 0 }

[filter]
some-data-to-constrain = { min = 0, max = 100000, dec = 2 }
some-data-to-remove = true
some-data-to-keep = false

[[generate]]
node = "some-node"
name = "some-name"
unit = "some-unit"
add = ["some-data-point-1","some-data-point-2"]
sub = ["some-data-point-3"]

[[generate]]
node = "some-other-node"
name = "some-other-name"
unit = "some-other-unit"
add = { node = "some-node",unit = "some-unit" } # not yet implemented
sub = ["some-specific-data-point"]
