# Configuration file for scraping data from static files.

# The settings section must minimally contain a declaration
# of the suffix of target files, Ex; `suffix = "csv"`.
# A `source` field may be specified to indicate where
# to look for the files to be converted.  If none is
# specified, `source` defaults to `tmp/inputs/project-name/`.
# Configuration templates are instantiated with the
# `is-active` field set to `false`.  Once the file has been
# properly configurated, this field must either be set
# to `true`, or deleted.
[settings]
is-active = false
suffix = "file-extension"
source = "path/to/files" # optional

# The pareser section must minimally declare the type of
# parser to be used, Ex; `type = "csv"`.  Any arguments that
# the specific perser implementation requires also go here,
# or in a sub-section.  Ex: `[parser.example]`.
[parser]
type = "some-parser"
# ...

# The `move-to` section is entirely optional.
# This section defines where to move the original
# files based upon wether parsing was successful,
# or encountered some kind of error.  These fields
# may be set to keywords `default` or `delete` as well.
[move-to]
on-fmt = "default" # default: `tmp/archive/projectname/static/`
on-err = "default" # default: `tmp/errors/projectname/static/`
