[acquire.static.settings]
is-active = true
source = '/usr/local/smb-share/hobo-12-raw/inputs/'
on-fmt = '/usr/local/smb-share/hobo-12-raw/archive/'
on-err = '/usr/local/smb-share/hobo-12-raw/errors/'

[[acquire.static.parser]]
parser = "hobocsv"
suffix = "csv"

[export.csv.settings]
is-active = true
directory = '/usr/local/smb-share/hobo-12-raw/outputs/'
file-spec = { tag = 'u12-data', timestamp = true }
