[acquire.static.settings]
is-active = true
source = '/usr/local/smb-share/hobo-12-raw/inputs/'
on-fmt = '/usr/local/smb-share/hobo-12-raw/archive/'
on-err = '/usr/local/smb-share/hobo-12-raw/errors/'
on-raw = 'tmp/outputs/hobo-u12/raw/' # default: `false`


[[acquire.static.parser]]
parser = "hobo-u12-csv"
suffix = "csv"

[export.csv.settings]
is-active = true
directory = '/usr/local/smb-share/hobo-12-raw/outputs/'
file-spec = { tag = 'u12-data', timestamp = true }
