[acquire.static.settings]
is-active = true
source = 'tmp/inputs/hobo-u12/'
on-fmt = 'tmp/archive/hobo-u12/'
on-err = 'tmp/errors/hobo-u12/'

[[acquire.static.parser]]
parser = "hobocsv"
suffix = "csv"

[export.csv.settings]
is-active = true
directory = 'tmp/outputs/hobo-u12/'
file-spec = { tag = 'u12-data', timestamp = true }
