# Configuration file for scraping data from static files.

# The settings section must minimally contain a declaration
# of the suffix of target files, Ex; `suffix = "csv"`.

[settings]
suffix = "file-extension"
source = "path/to/files" # Optional; defaults to tmp/inputs/projectname/


# The pareser section must minimally declare the type of
# parser to be used, Ex; `type = "csv"`.  Any arguments that
# the specific perser implementation requires also go here.

[parser]
type = "some-parser"
# ...
