# Configuration file for webCTRL API scrape.
# The settings section must contain login info
# in the form `login = { name = "uname", pass = "pass" }`.

[settings]
login = { name = "uname", pass = "pass" }
server = "http://some.webctrl.server/api/endpoint/"


# The sensor section may contain any number of sensors
# with the minimal form being:
# [[sensors]]
# name = "sensor-name"
# path = "path/to/sensor"

[[sensors]]
node = "some-node" # optional field; defaults to project name.
name = "some-name"
unit = "some-unit" # optional field; defaults to "undefined".
path = "ABSPATH:some/path/to/data/"

# ...
