# Configuration file for CSV based data-export.
# The `csv` export method is specifically designed
# to be trivial to instantiate for debug purposes.
# As a result, one can choose to simply add
# `csv = true` to the `[export]` section of a
# project's primary config file if no
# special configurations are required.

# Miscellaneous Settings
[settings]
is-active = true
file-prefix = "raw"
