[acquire]
type = "egauge"

[acquire.gauges]
maui-smart-grid = 787

[reshape]
field-file = "field-map"
value-file = "value-map"

[[reshape.extra]]
type = "current-time"
name = "upload_timestamp"



[export]
csv = true
psql-file = "psql-config"
