[data-point]
node = "frog-1"
sensor = "other-avg"
unit = "kW"

[expect]
add-count = 1
sub-count = 11

[add.include]
node = "frog-1"
unit = "kW"
sensor = "whole-building-avg"

[sub.include]
node = "frog-1"
unit = "kW"
sensor = "*-avg"

[sub.exclude]
sensor = "whole-building-avg"
