[general]
is-active = false
database = "frog_uhm"
table = "reading"

[conversions]
datetime = "to-timestamp"
upload_timestamp = "to-timestamp"

[filter]
time-index = 
unique-key = ["datetime","purpose_id"]
